### ISSUE TITLE
[Change Proposal] Validating event.original implementation + ECS version in pipeline

### ISSUE THREAD

**Issue by P1llus** [elastic/package-spec#177]
This Issue is to track the possibility to both add these specific fields to the package-spec for newly created packages + linting to make sure they exist.

Currently these are the changes:
**Event.original implementation:** (Example can be found on the apache package)
The `manifest.yml` should have this option for all non-metric packages (is this possible to differentiate?)
```
    vars:
      - name: preserve_original_event
        required: true
        show_user: true
        title: Preserve original event
        description: Preserves a raw copy of the original event, added to the field `event.original`
        type: bool
        multi: false
        default: false
```

The HBS file should include:
```
tags:
{{#if preserve_original_event}}
  - preserve_original_event
{{/if}}
{{#each tags as |tag i|}}
- {{tag}}
{{/each}}
```

In the pipeline these two processors should be included:
At the top
```
  - rename:
      field: message
      target_field: event.original
      ignore_missing: true
```
At the bottom:
```
  - remove:
      field: event.original
      if: "ctx?.tags == null || !(ctx.tags.contains('preserve_original_event'))"
      ignore_failure: true
      ignore_missing: true

```
The common pipeline test file should at least set the preservation tag:
```
fields:
  tags:
    - preserve_original_event
```

**ECS versions implementation**
All pipelines for packages that are non-metrics (since they put ECS versions in code instead) should have a pipeline processor like this:
```
  - set:
      field: ecs.version
      value: "1.10.0"
```

**Allow Custom processors**
To be able to allow custom processors, all packages should have these changes:
HBS files:
```
processors:
{{processors}}
```
Menu item in manifests:
```
      - name: processors
        type: yaml
        title: Processors
        multi: false
        required: false
        show_user: false
        description: >
          Processors are used to reduce the number of fields in the exported event or to enhance the event with metadata. This executes in the agent before the logs are parsed. See [Processors](https://www.elastic.co/guide/en/beats/filebeat/current/filtering-and-enhancing-data.html) for details.
```
