### ISSUE TITLE
Enabled/disabled data stream depending on policy template

### ISSUE THREAD

**Issue by narph** [elastic/package-spec#195]
Ex Azure Resource Metrics package, we would like to have only the main metricset enabled where custom metrics can be retrieved and then leave it up to users to enable which resource types they would like to monitor.
Ex:

![image](https://user-images.githubusercontent.com/1900090/124756044-f6a83400-df23-11eb-8563-ba5dea60988a.png)

We achieved this by setting `enabled : false` at the data stream level.

but if users select from the category list to monitor Virtual Machines 

![image](https://user-images.githubusercontent.com/1900090/124756331-40911a00-df24-11eb-841f-26f2858beb51.png)

then we also see the data stream disabled, this will be an extra step for the user to enable it although he purposefully chose to monitor this type of resource from the list. 

![image](https://user-images.githubusercontent.com/1900090/124756398-5272bd00-df24-11eb-9ba5-f0ea1213c5ef.png)

Can we have a similar flag either at the template policy level where we can decide which data streams can be enabled/disabled?

**Comment by mtojek** [comment]
cc @jen-huang @ruflin @sorantis

**Comment by sorantis** [comment]
With more packages supporting granularity this behavior is becoming commonplace. What's the solution for improving the UX here?

**Comment by narph** [comment]
@jen-huang , can you provide us with any feedback here

**Comment by jen-huang** [comment]
What about adding an `enabled: boolean` field to `policy_templates.inputs` items?

https://github.com/elastic/package-spec/blob/a7173524bc764d62fd80db0b3d2b0b10419285c1/versions/1/manifest.spec.yml#L207

Values of `true`/`false` are self explanatory. If undefined, it will coerce based on if any of that policy template's streams are enabled (same as today)([LOC](https://github.com/elastic/kibana/blob/fa64146244912204974265cb3a2171ee6daba872/x-pack/plugins/fleet/common/services/package_to_package_policy.ts#L122)).

**Comment by narph** [comment]
hi @jen-huang , I did not know that existed, I did not see docs for it, either way, I cannot make this option work both on 7.14 and 7.15 snapshots.
Ex:

```
policy_templates:
....
  - name: storage_account
    title: Azure Storage Account metrics
    description: Azure Storage Account Metrics Integration
    data_streams:
      - storage_account
    inputs:
      - type: "azure/metrics"
        title: "Collect Azure Storage Account metrics"
        description: "Collecting Azure Storage Account metrics"
        input_group: metrics
        enabled: true
    icons:
      - src: /img/storage_account_logo.png
        title: logo azure
        size: 32x32
        type: image/svg+xml
    screenshots:
      - src: /img/docker-overview.png
        title: filebeat azure overview
        size: 5002x2666
        type: image/png
```

![image](https://user-images.githubusercontent.com/1900090/130444387-db3636bc-6c48-4775-8545-db3b9fcaea0a.png)


What am I missing here?
