### ISSUE TITLE
[Change Proposal] Add support for specifying Elasticsearch privileges

### ISSUE THREAD

**Issue by axw** [elastic/package-spec#203]
In https://github.com/elastic/kibana/pull/94591 and https://github.com/elastic/kibana/pull/97366, Kibana added support for informing fleet-server of the privileges that should be assigned to an agent API Key. There was mention of a pending proposal in one of the PRs for packages to specify privileges ("permissions"):

> To do so we look into the policy's PacakgePolicy and the enabled inputs. We link that with the package DataStream to determine which indices it uses and which permissions it needs. The permissions will be specified in the package's data_streams/*/manifest.yml (pending proposal).

We would like to do just this in APM Server, to enable servers to periodically refresh and read a single non-sensitive data stream: https://github.com/elastic/apm-server/issues/5490. Specifically, we require the `maintenance` and  `read` index privileges for the `traces-apm.sampled-*` index pattern. I don't think the proposal was ever made, so I'm proposing it now.

[The way the Kibana code is written](https://github.com/elastic/kibana/blob/e771748d96ba098e2e35cf98a010f4f2a23c9c39/x-pack/plugins/fleet/common/types/models/epm.ts#L300), a `permissions` property would be expected in `data_stream/<data_stream>/manifest.yml`, e.g.

```yaml
title: APM tail-sampled traces
type: traces
dataset: apm.sampled
ilm_policy: traces-apm.sampled-default_policy
permissions:
  cluster: ['monitor']
  # Additional index privileges are required for tail-based sampling:
  #   maintenance: for refreshing sampling decisions
  #   read: for reading sampling decisions
  indices: ['auto_configure', 'create_doc', 'maintenance', 'read']
elasticsearch:
  index_template:
    settings:
      # Create a single shard per index, so we can use
      # global checkpoints as a way of limiting search
      # results.
      number_of_shards: 1
```

Given that these permissions are Elasticsearch privileges, I think it might make more sense to define them as such explicitly. e.g.

```yaml
title: APM tail-sampled traces
type: traces
dataset: apm.sampled
ilm_policy: traces-apm.sampled-default_policy
elasticsearch:
  privileges:
    cluster: ['monitor']
    indices: ['auto_configure', 'create_doc', 'maintenance', 'read']
  index_template:
    settings:
      # Create a single shard per index, so we can use
      # global checkpoints as a way of limiting search
      # results.
      number_of_shards: 1
```

Implementation issues:
 1. [x] https://github.com/elastic/package-spec/issues/210
 2. [x] https://github.com/elastic/package-registry/issues/712
 3. [x] https://github.com/elastic/kibana/issues/109047
