### ISSUE TITLE
Add support for specifying Elasticsearch privileges in data stream manifest

### ISSUE THREAD

**Issue by axw** [elastic/package-spec#210]
Per https://github.com/elastic/package-spec/issues/203#issuecomment-891827816, extend the spec to allow defining Elasticsearch privileges for a data stream. This will be achieved by introducing `elasticsearch.privileges.indices` as an optional property in data stream manifests, e.g.

```yaml
title: APM tail-sampled traces
type: traces
dataset: apm.sampled
ilm_policy: traces-apm.sampled-default_policy
elasticsearch:
  privileges:
    indices: ['auto_configure', 'create_doc', 'maintenance', 'monitor', 'read', 'read_cross_cluster']
```
