### ISSUE TITLE
[Change Proposal] Allow setting `dynamic` field on external fields

### ISSUE THREAD

**Issue by marclop** [elastic/package-spec#251]
## Problem description

Currently, it is possible to reference an ECS field in a data stream mapping template, data stream settings can cause some fields to not work as intended when the data stream `dynamic` field is set. For instance, in APM Server we currently have some data streams where we set to a `dynamic: strict|false`, this causes some fields that are dynamic by nature to not work as intended.

## Proposed change

To address the described problem, it would be ideal if we could set `dynamic` for external fields on a field level, so that there can be exceptions to settings defined for the data stream.

```yaml
- external: ecs
  name: labels
  dynamic: true
```

## Current workaround.

Currently, we have to re-declare the `labels` field since it would otherwise not work as intended in all the APM Server data streams:

```yaml
- name: labels
  type: object
  dynamic: true
```
