### ISSUE TITLE
[Change Proposal] Allow empty changelogs on packages with stack-aligned versions

### ISSUE THREAD

**Issue by marclop** [elastic/package-spec#254]
## Description

It would be great if there was a way for packages with versions that are aligned with the Stack to have empty changelogs or have a type of change `empty` so the `elastic-package` linting passes.
Many packages are likely to be forward looking when in development stages and are also likely to not have significant changes just after the version has been bumped.

## Why

`apm-server` (and I assume other packages too) have package versions that are aligned with the stack and are forward looking, such as `8.0.0` and `8.1.0` at the moment this issue was written.

In order to be able to commit an unreleased package without any changes, it would be great to relax the required changelog entry check to avoid adding changelog entries such as:

```yaml
- version: "8.1.0"
  changes:
    - description: REPLACE ME WITH ACTUAL CHANGE LOG
      type: enhancement
      link: https://github.com/elastic/apm-server/pull/1234
```

See https://github.com/elastic/apm-server/pull/6676#discussion_r753156605.

**Comment by jsoriano** [comment]
Hey @marclop,

If I understand well, versions aligned with the stack have at least the change in the version constraint (`kibana.version: "^8.1.0"`), that I think is worth of a changelog entry such as:
```
- version: "8.1.0"
  changes:
    - description: Support Kibana 8.1.0.
      type: enhancement
      link: https://github.com/elastic/apm-server/pull/6676
```

Would this cover your case?

Having completely empty changelogs for other cases would only make sense if a new version wants to be released with exactly the same code, including the manifest, but I cannot think on a use case for this.
