### ISSUE TITLE
[Change Proposal] Provide human-readable name to integration inputs

### ISSUE THREAD

**Issue by juliaElastic** [elastic/package-spec#385]
Proposal coming from the discussion in https://github.com/elastic/kibana/issues/132263

Creating an integration (package-policy) with Fleet API requires specifying input types, and its meaning is not obvious for users.

Could we extend package-spec with a new field in inputs, that would be a human-readable value?
This would make it easier for users to create integrations.

Current API:
```
POST http://elastic:changeme@localhost:5601/julia/api/fleet/package_policies
kbn-xsrf: kibana

{
  "name":"apache-5",
  "inputs": [
    {"type":"logfile","enabled":true},
    {"type":"apache/metrics","enabled":false}
  ],
  "package": {
    "name":"apache",
    "version":"0.3.3"
  }
}
```

Proposed change:
```
	"inputs": [
	  {"id":"apache_logs","enabled":true},
	  {"id":"apache_metrics","enabled":false}
	],
```

cc @joshdover

**Comment by jsoriano** [comment]
Thanks for opening this proposal, I think it makes sense, this will also help to solve issues like the ones mentioned in https://github.com/elastic/package-spec/issues/383.

Going into the details, the proposal would be to allow something like the following, right? So each input has a unique identifier inside the package:
```
...
policy_templates:
  - name: apache
    title: Apache logs and metrics
    description: Collect logs and metrics from Apache instances
    inputs:
      - id: apache_logs
        type: logfile
        title: Collect logs from Apache instances
        description: Collecting Apache access and error logs
...
```
Would this id be needed also in the data_stream manifest to co-relate the input in the policy template with its specific data stream? It could be then something like this:
```
title: Apache access logs
type: logs
streams:
  - id: apache_logs
    input: logfile
    vars:
...
```

> The proposed change would require updating all packages' inputs with unique id values.

I think we shouldn't make changes that require updating all packages. We need to continue supporting packages currently released. At least till next major.
