### ISSUE TITLE
[Custom-agent deployer] Remove validation to allow Dockerfile in the Integration_package/datastream/deploy/agent 

### ISSUE THREAD

**Issue by agithomas** [elastic/package-spec#438]
There exist a validation to allow only one service in custom-agent

This does not allow system testing configuration such as below. 

This method helps to have Dockerfile become part of the package

```
version: '2.3'
services:
docker-custom-agent:
build:
      context: .
      dockerfile: Dockerfile.oracle
user: root
oracle:
image: docker.elastic.co/observability-ci/database-enterprise:12.2.0.1
ports:
- 1521:1521
- 5500:5500
```
