### ISSUE TITLE
[Change Proposal] Support index template -> data_stream -> hidden boolean

### ISSUE THREAD

**Issue by kpollich** [elastic/package-spec#464]
The package spec doesn't expose a way to set the `data_stream.hidden` property on generated index templates, resulting in some hacky workarounds for some use cases. We should expose this setting directly in the `data_stream/**/manifest.yml` file, e.g. 

```yml
# some_package/data_stream/foo/manifest.yml
title: Foo
dataset: foo.bar
elasticsearch:
  index_template:
     data_stream:
       hidden: true
```
