### ISSUE TITLE
[Change Proposal] Add benchmark definitions to packages

### ISSUE THREAD

**Issue by marc-gr** [elastic/package-spec#483]
In order to keep adding benchmarking capabilities to `elastic-package`, a definition for benchmarking scenarios would be useful to define and run end-to-end benchmarks for packages.

An initial simple benchmark definition would consist of:

- The target package version
- The target data-stream
- The variables to set up the policy
- Some basic settings to control warm-up and ramp-up (similar to [the ones available in rally](https://esrally.readthedocs.io/en/stable/track.html#schedule))
- Settings to define corpora sources (ie. local or S3 to begin with)
- Settings to define how the corpora logs will be sent to the agents (initially we can leverage the [stream tool](https://github.com/elastic/stream) that is currently used for system tests)

A tentative spec definition could look like:

`spec.yml`
```yaml
spec:
  additionalContents: false
  developmentFolder: true
  contents:
    - description: Folder containing end-to-end benchmarks scenarios.
      type: folder
      name: e2e
      required: false
      additionalContents: true
      contents:
        - description: Folder containing docker compose files for benchmarks.
          type: folder
          name: deploy
          additionalContents: true
          required: false
          contents:
            - description: Docker Compose configuration file for deploying benchmarks additional services.
              type: file
              name: "docker-compose.yml"
              contentMediaType: "application/x-yaml"
              required: true
        - description: A benchmark scenario.
          type: file
          pattern: '^.+\.yml$'
          contentMediaType: "application/x-yaml; require-document-dashes=true"
          required: false
          $ref: './scenario.spec.yml'
```

`scenario.spec.yml`
```yml
spec:
  type: object
  additionalProperties: false
  properties:
    version:
      description: The package version to benchmark.
      required: true
    data_stream:
      description: The data-stream to benchmark.
      required: true
    description:
      description: A description of the benchmark scenario.
      required: true
    corpora:
      description: Corpora settings.
      required: true
      type: object
      additionalProperties: false
      properties:
        path:
          description: The local path to the corpora.
        s3_bucket:
          description: The S3 bucket containing the corpora.
    input_service:
      description: The service (found in ./deploy) that will send corpora logs to the elastic agents.
    warmup-time-period:
      description: A time period in seconds for warmup of the benchmark. All response data captured during warmup will not show up in the measurement results.
```

**Comment by aspacca** [comment]
> ```yaml
>     corpora:
>       description: Corpora settings.
>       required: true
>       type: object
>       additionalProperties: false
>       properties:
>         path:
>           description: The local path to the corpora.
>         s3_bucket:
>           description: The S3 bucket containing the corpora.
> ```

suggestion:
```
      properties:
        generate:
          description: The flag that indicates if the corpus has to be generated or fetched
        path:
          description: The local path to the corpora.
        s3_bucket:
          description: The S3 bucket containing the corpora.
```
