### ISSUE TITLE
Multiple modules, only one config set

### ISSUE THREAD

**Issue by mtojek** [elastic/package-spec#51]
I received this question from @fearful-symmetry today. Let's discuss it here - 

Is it possible to have an integration with multiple modules but only one config set? Like, the only way I know to link the integration to a given module is to use config templates:

```
config_templates:
  - name: system
    title: System logs and metrics
    description: Collect logs and metrics from System instances
    inputs:
      - type: logfile
        title: Collect logs from System instances
        description: Collecting System auth and syslog logs
      - type: system/metrics
        title: Collect metrics from System instances
        description: Collecting System core, CPU, diskio
```

But this will produce two config sets, one for `Collect logs from System instances` in the `logfile` module, and one for `Collect metrics from System instances` from the `system/metrics` module. Is there a way to just get one config set for an arbitrary number of modules?

/cc @ruflin @ycombinator

**Comment by ruflin** [comment]
What is a config set for you? Can you perhaps share an example end result yaml file or similar you would like to see outputed by Fleet for the Agent?

**Comment by fearful-symmetry** [comment]
@ruflin  So, right now I'm working on a linux integration which will include parts of the `linux` and `system` module in metricbeat. No matter what, the config always seems to end up like this. If there's some way to connect to two metricbeat modules with only one config visible in the frontend, I haven't figured it out.

<img width="822" alt="Screen Shot 2020-09-29 at 7 00 57 AM" src="https://user-images.githubusercontent.com/8418476/94568612-92807300-0221-11eb-892f-e0eba7776221.png">

**Comment by ruflin** [comment]
Got it. You want to combine two inputs under 1. Unfortunately this is not possible at the moment. The basic assumption was that everything is grouped by inputs to share common input configs. 

Is it correct that these are 2 different inputs / modules?

**Comment by fearful-symmetry** [comment]
Yep. Right now we have two linux-only data spread across the system module and the linux module.

**Comment by fearful-symmetry** [comment]
So, it looks like we're running into this on the system module too, as we need a dynamic input guard for `system/load`, which requires a separate input.

**Comment by fearful-symmetry** [comment]
Any updates on this?

**Comment by ruflin** [comment]
@fearful-symmetry Any chance you could do 2 things here:

* Paste the final agent config on how it will look
* Draw a very rough wireframe on how you think it should look in our UI (very high level)

I think this will help us to move this forward quickly.

**Comment by fearful-symmetry** [comment]
@ruflin, alright, lemme see what I can do...

**Comment by fearful-symmetry** [comment]
@ruflin 

Okay, one way to do this would be to make a separate "config group" section. Here's a theoretical integration-level `manifest.yml`:
```
config_groups:
    - name: logs
      title: Collect logs from System instances
      description: Collecting System auth and syslog logs
    - name: metrics
      title: Collect metrics from System instances
      description: Collecting System core, CPU, diskio, entropy, filesystem, fsstat, load, memory, network, Network Summary, process, Process Summary, raid, service, socket, Socket Summary, uptime and users metrics
policy_templates:
  - name: system
    title: System logs and metrics
    description: Collect logs and metrics from System instances
    inputs:
      - type: logfile
        group: logs
      - type: winlog
        group: logs
        condition: ${host.platform} == 'windows'
      - type: system/metrics
        group: metrics
```

We could also do away with defining the inputs in the integration-level manifest, limit it to the `config_groups`, and then define inputs at the data_stream manifest.yml level:

```
title: System core metrics
release: experimental
type: metrics
streams:
  - input: system/metrics
    config_group: metrics
    enabled: false
    vars: [...]
```


Does that make sense? I'm not sure what A wireframe would show here, since in theory it should look just the same as what the system integration looks like now (in 7.10 at least). The idea is to "hide" a multiplicity of inputs from the user, so that two config groups (logs and metrics, for example) can be mapped to any number of inputs. Going the other way around, we can have multiple config groups mapped to some number of inputs. We can have any number of config groups now, but they must have a 1:1 relationship with inputs. For example: 
<img width="1048" alt="Screen Shot 2020-11-25 at 10 10 31 AM" src="https://user-images.githubusercontent.com/8418476/100266515-cbc61e00-2f06-11eb-9481-e6f49699b3df.png">
