### ISSUE TITLE
[Fleet] Add support for routing rules in integrations

### ISSUE THREAD

**Issue by kpollich** [elastic/package-spec#514]
In order to support document-based routing in Fleet, integrations need to expose their routing rules as part of their data stream manifest files.

These rules would be translated to [`reroute` processors](https://www.elastic.co/guide/en/elasticsearch/reference/master/reroute-processor.html) appropriately by Fleet during integration installation.

A routing rule is composed of a few pieces of data:
- "Source" dataset: in which dataset should Fleet place this rule?
- "Destination" dataset: where should documents be routed by this rule?
- Condition: what logic determines when a document is routed?
- Namespace: under what namespace should this document be written once routed?

We'll need to support two types of routing rules defined by an integration:
- "Local" routing rules that route from a dataset on a given integration to other datasets on that same integration
- "Injected" routing rules that route from a dataset on a _external_ integration back to the given integration

As far as integrations are concerned, though, there is no meaningful difference between writing a "local" routing rule and an "injected" routing rule in a data stream manifest. Fleet will be responsible for generating the appropriate `processors` in the appropriate ingest pipelines based on these rules. So, the implementation on the package-spec side will be a generic `routing_rules` object at the data stream manifest level.

Typically, routing rules will be defined on a "catch-all" or "data sink" style dataset like `kubernetes.router` that is essentially a passthrough to more specific data streams.

For example, we might have an `nginx` catch-all dataset that routes Nginx logs to more specific data sets like `nginx.error` and `nginx.access` based on the logfile path reported in each document.

Here's a proposed example of the above in action. Please see the annotative comments for more details:

```yml
# nginx/data_stream/nginx/manifest.yml
title: Nginx logs
type: logs

# This is a catch-all "sink" data stream that routes documents to 
# other datasets based on conditions or variables
dataset: nginx

# Ensures agents have permissions to write data to `logs-nginx.*-*`
elasticsearch.dynamic_dataset: true
elasticsearch.dynamic_namespace: true

routing_rules:
  # "Local" routing rules are included under this current dataset, not a special case
  nginx:
    # Route error logs to `nginx.error` when they're sourced from an error logfile
    - dataset: nginx.error
      if: "ctx?.file?.path?.contains('/var/log/nginx/error')"
      namespace:
        - {{labels.data_stream.namespace}}
        - default

    # Route access logs to `nginx.access` when they're sourced from an access logfile
    - dataset: nginx.access
      if: "ctx?.file?.path?.contains('/var/log/nginx/access')"
      namespace:
        - {{labels.data_stream.namespace}}
        - default
  
  # Route K8's container logs to this catch-all dataset for further routing
  k8s.router: 
    - dataset: nginx
      if: "ctx?.container?.image?.name == 'nginx'"
      namespace:
        - {{labels.data_stream.namespace}}
        - default
   
  # Route syslog entries tagged with nginx to this catch-all dataset
  syslog:
    - dataset: nginx
      if: "ctx?.tags?.contains('nginx')"
      namespace:
        - {{labels.data_stream.namespace}}
        - default

```

Fleet support will be implemented as follow:
- Phase 1: https://github.com/elastic/kibana/issues/155910
- Phase 2: https://github.com/elastic/kibana/issues/157422

**Comment by juliaElastic** [comment]
> * Are these two settings mandatory for every package that uses routing rules ?
>   ```yaml
>   # Ensures agents have permissions to write data to `logs-nginx.*-*`
>   elasticsearch.dynamic_dataset: true
>   elasticsearch.dynamic_namespace: true
>   ```
>   To avoid defining this in every package (datastream) using routing rules, could it be done automatically by Fleet when installing the package if any routing rule is defined ?

I think it makes sense to add this during Fleet installation to avoid repeating in every package, it seems mandatory if `routing_rules` are present. We can add it as a task in https://github.com/elastic/kibana/issues/155910

> * In this example, it is used `dataset` that it is [already defined in package-spec](https://github.com/elastic/package-spec/blob/5e86c23605e14f5800a966a7ab535ef106b5f0b8/spec/integration/data_stream/manifest.spec.yml#L173):
>   ```yaml
>   # This is a catch-all "sink" data stream that routes documents to 
>   # other datasets based on conditions or variables
>   dataset: nginx
>   ```
>   Should it be updated the description ? Should we add another key for this ?

I think it's good to use the existing data stream.

> * Checking how to define this new `routing_rules` key in package-spec:
>   
>   * As each data-stream manifest could be very long, I was thinking to move this definition to its own file inside the data-stream folder, is that ok?

I think it makes sense to add to its own file.

>   * I was wondering if this could be rewritten as an array of objects:
>     
>     * instead of `name`, would it better `dataset` or another naming?
>     
>     ```yaml
>     routing_rules:
>       - name: nginx
>         rules:
>           - dataset: ...
>       - name: k8s.router
>         rules:
>           - dataset: ... 
>     ```

I think array of objects sounds good.
The name refers to the package name, so we could call it `package` (which will be always the same as the current package in the first phase e.g. nginx)

**Comment by mrodm** [comment]
> > * In this example, it is used `dataset` that it is [already defined in package-spec](https://github.com/elastic/package-spec/blob/5e86c23605e14f5800a966a7ab535ef106b5f0b8/spec/integration/data_stream/manifest.spec.yml#L173):
> >   ```yaml
> >   # This is a catch-all "sink" data stream that routes documents to 
> >   # other datasets based on conditions or variables
> >   dataset: nginx
> >   ```
> >   
> >     
> >   Should it be updated the description ? Should we add another key for this ?
> 
> I think it's good to use the existing data stream.

Just one more question about this.  Should `dataset` field be mandatory in case `routing_rules` key is defined ? @juliaElastic 
If so, probably `routing_rules` should be defined at the same manifest file so it can be expressed that requirement.

**Comment by mrodm** [comment]
Once https://github.com/elastic/package-spec/pull/535 has been completed.
These routing rules are going to be defined in its own file in each data stream folder. For instance:
- `data_stream/rules/routing_rules.yml`

And this is one example of the contents/syntax of this file:

```yaml
  # "Local" routing rules are included under this current dataset, not a special case
- source_dataset:  nginx
  # Route error logs to `nginx.error` when they're sourced from an error logfile
  - target_dataset: nginx.error
    if: "ctx?.file?.path?.contains('/var/log/nginx/error')"
    namespace:
      - {{labels.data_stream.namespace}}
      - default

  # Route access logs to `nginx.access` when they're sourced from an access logfile
  - target_dataset: nginx.access
    if: "ctx?.file?.path?.contains('/var/log/nginx/access')"
    namespace:
      - {{labels.data_stream.namespace}}
      - default
  
# Route K8's container logs to this catch-all dataset for further routing
- source_dataset: k8s.router
  - target_dataset: nginx
    if: "ctx?.container?.image?.name == 'nginx'"
    namespace:
      - {{labels.data_stream.namespace}}
      - default
   
  # Route syslog entries tagged with nginx to this catch-all dataset
- source_dataset: syslog
  - target_dataset: nginx
    if: "ctx?.tags?.contains('nginx')"
    namespace:
      - {{labels.data_stream.namespace}}
      - default
```
