### ISSUE TITLE
[Fleet] Add support for handlebars templating in `fields/*.yml` and `ingest_pipeline/*.yml` files

### ISSUE THREAD

**Issue by kpollich** [elastic/package-spec#517]
In order to support the concept of "data fidelity modes" in Fleet/Integrations, we'll need to support template configuration for mappings and ingest pipelines. The goal here is to allow integration maintainers to define the set of fields and processors for each fidelity mode supported by the integration. 

For example, an ingest pipeline configuration might contain a block like 

```yml
{{#if high_fidelity_mode}}
  - remove:
      field: apache.error.timestamp
      ignore_failure: true
{{/if}}
```

to drop the `timestamp` field from apache errors. This allows integration maintainers to decide how and where the savings (or lack thereof) related to data fidelity are applied.
