### ISSUE TITLE
[Change Proposal] Add different validation modes for source and built packages

### ISSUE THREAD

**Issue by jsoriano** [elastic/package-spec#549]
Now we are using the very same spec to validate source and built packages, but the content can be actually different. For example dev files or external fields can be found in source packages but are not expected to be on built packages. Adding two validation modes can allow us to be more strict with the content and format of built packages. It can also help on testing package build implementations like the one in `elastic-package`.

We would need to:
* Expose in the `validator` package an interface to select the validation mode.
* Define somehow in the spec the contents for each mode.

**Comment by jsoriano** [comment]
This can be also relevant for link files, introduced in https://github.com/elastic/package-spec/pull/888.

In this case link files should be allowed in the source, but not in built packages.

**Comment by Supplementing** [comment]
Do we have a clear breakdown somewhere of whats expected vs not in each @jsoriano? I'd like to take a pass at this if its okay, but as someone who's not as 'in the know', that would be helpful to have!

**Comment by jsoriano** [comment]
Just FTR, as discussed over Slack we don't have a clear breakdown. Part of this task would be to do this assessment.

We can also start by introducing the initial framework to have different validation modes, and have three: `legacy`, `source` and `build`. `legacy` would be the current validation mode, and we would start using `source` and `build` when they are ready.

**Comment by Supplementing** [comment]
Bumping this on open questions that need addressing so we can move forward. The following are hard blockers that need answered:

OQ#1 — API shape: A (extra param), B (functional options), or C (validator constructor)? 

- We soft committed to C, need confirmation that this is acceptable and preferred. 


OQ#2 — Auto-detect mode from package contents, or require explicit pass? Tradeoff: caller ergonomics vs. risk of silent misclassification.

- As discussed in the original doc, both have their pros and cons. Ideally, since we control what goes into a built package,we should be able to easily tell what is a built vs a source package and therefore auto-detecting would be preferable. Open to thoughts here and need final sign-off here. 


OQ#5 — Composable packages in build mode. A built composable package may not be structurally distinguishable from a regular integration package. Either an additional signal is needed for build-mode validation, or the design needs to absorb the ambiguity. See https://github.com/elastic/elastic-package/issues/3277.

- Its not super clear here what the best path is, maybe someone from the ecosystem team can add their thoughts around whether absorbing is safe or if we need additional signal(s).

**Comment by teresaromero** [comment]
@Supplementing these are my thoughts on the blockers, thanks!


>OQ#1 — API shape: A (extra param), B (functional options), or C (validator constructor)?

I am missing some context here as i don't have access to the RFC comments, but i would lean on the validator constructor if that means separate rules by modes and having a clear distinction. Then we could call one or the other with elastic-package to use explicitly (related to next comment)

>OQ#2 — Auto-detect mode from package contents, or require explicit pass? Tradeoff: caller ergonomics vs. risk of silent misclassification.

In general, I'd prefer explicit over implicit behavior. My suggestion:

- Default to `source` validation, with a flag to opt into `build` validation
- If `autodetect` is chosen, make the output explicit about which mode was resolved — avoids misinterpretation

Also, some commands require validation in a specific mode, so we should support forcing a mode to guarantee the package being referenced is unambiguously a `build` or `source`.

>OQ#5 — Composable packages in build mode. A built composable package may not be structurally distinguishable from a regular integration package. Either an additional signal is needed for build-mode validation, or the design needs to absorb the ambiguity. See https://github.com/elastic/elastic-package/issues/3277.

related to composable, a composable package should be same as a regular integration package. I dont think once bundled they will need any different parameter. One case that has come while implementing, is an policy template which ends up with multiple inputs of the same type, which has been solved by assigning a name field to idenitfy it. this is already placed on the bundle, so when validating a bundle it should not require a distinction.

**Comment by jsoriano** [comment]
> OQ#1 — API shape: A (extra param), B (functional options), or C (validator constructor)?
> * We soft committed to C, need confirmation that this is acceptable and preferred.

+1 on option C. Apart from helping on this case it will also help to introduce further options in the future.

> OQ#2 — Auto-detect mode from package contents, or require explicit pass? Tradeoff: caller ergonomics vs. risk of silent misclassification.
> * As discussed in the original doc, both have their pros and cons. Ideally, since we control what goes into a built package,we should be able to easily tell what is a built vs a source package and therefore auto-detecting would be preferable. Open to thoughts here and need final sign-off here.

I would require a explicit pass. This is a validator, so the caller should be able to decide and control what they want to validate.

Auto-detection should have zero risk of misclassification, I would prefer not even needing to think about how we can guarantee that.

> OQ#5 — Composable packages in build mode. A built composable package may not be structurally distinguishable from a regular integration package. Either an additional signal is needed for build-mode validation, or the design needs to absorb the ambiguity. See [elastic/elastic-package#3277](https://github.com/elastic/elastic-package/issues/3277).
> * Its not super clear here what the best path is, maybe someone from the ecosystem team can add their thoughts around whether absorbing is safe or if we need additional signal(s).

Why do we need to distinguish composable packages?

As "composable packages" have been implemented they are a set of new features for regular integration packages, so at the end they are the new regular integration packages 🙂

The relationship of this task in the "composable packages" project is that integration packages build becomes much more complex when dependencies are used, and it is specially worth to be able to have different validation methods for source and built packages.

**Comment by mrodm** [comment]
> Why do we need to distinguish composable packages?
> 
> As "composable packages" have been implemented they are a set of new features for regular integration packages, so at the end they are the new regular integration packages 🙂
>

@jsoriano @teresaromero I was wondering if it is needed to add some different checks in integrations packages that are defined as composable packages. For instance in a data stream manifest (from source):
- there could be a `package` field
- no need to be present an `input` field

```yaml
title: Nginx access logs
type: logs
streams:
  - package: filelog_otel
    title: Nginx access logs via filelog OTel receiver
    description: Collect Nginx access log files using the filelog receiver from the filelog_otel input package.
    vars:
      - name: include
        type: text
        title: Include paths
        multi: true
        required: false
        show_user: true
        secret: false
        description: Glob patterns for Nginx access log files.
        default:
          - /var/log/nginx/access.log*
```

however, in the built package
- `package` setting is not there
- `input` must be added


```yaml
title: Nginx access logs
type: logs
streams:
  - title: Nginx access logs via filelog OTel receiver
    description: Collect Nginx access log files using the filelog receiver from the filelog_otel input package.
    vars:
      - name: include
        required: false
        title: Include paths
        description: Glob patterns for Nginx access log files.
        type: text
        multi: true
        show_user: true
        secret: false
        default:
          - /var/log/nginx/access.log*
      - ...
    template_paths:
      - filelog_otel-input.yml.hbs
    input: filelog_otel
...
```
