### ISSUE TITLE
Add support for routing rules or pre-defined pipelines in input packages

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/package-spec#566]
We want to create a new input package called `AWS Firehose` that streams logs (and metrics in the future) from Amazon Kinesis Data Firehose into Elastic Stack. This input package needs to reroute incoming logs/metrics to different data streams based on the pre-defined rerouting rules or pipelines.

For example: We would like to route the log entry to `aws.cloudtrail` dataset if the value of `aws.cloudwatch.log_stream` field has `CloudTrail` in there.
```
processors:
  - reroute:
    if: ctx['aws.cloudwatch.log_stream'].contains('CloudTrail')
    dataset: aws.cloudtrail
    namespace: default
```

Either supporting routing rules directly or supporting pre-defined pipelines will work for our use case.
