### ISSUE TITLE
Add new validation rule to avoid rename processor without checking event.original

### ISSUE THREAD

**Issue by mrodm** [elastic/package-spec#583]
Originally posted in https://github.com/elastic/integrations/issues/3451#issuecomment-1693521101

Add a new validation rule to ensure that if there is a rename processor whose target_field is `event.original` and `field` is `message`, it needs also to check that `if`  key is defined checking about the presence of `event.original` in the document.

Moreover this new validation rule needs to check that a `remove` processor is defined to remove the `message` field, to avoid duplication.

As an example, if there is that rename processor in the ingest pipeline, a remove processor should exist and that rename processor should be like :
```yaml
    - rename:
        field: message
        target_field: event.original
        # ignore_missing: true 
        if: 'ctx.event?.original == null'
    - remove:
        field: message
        ignore_missing: true
        if: 'ctx.event?.original != null'
```

Similar to what it was done in https://github.com/elastic/integrations/pull/7026
