### ISSUE TITLE
Add support for flattened type dimensions

### ISSUE THREAD

**Issue by gpop63** [elastic/package-spec#584]
Currently, `flattened` type cannot be a dimension.  This limitation restricts us from effectively utilizing flattened fields within TSDB enabled data streams. The point of this is enhancing the existing functionality by allowing the declaration of multiple values as dimensions, even when they are flattened.

```yaml
- name: dimensions
  type: flattened
  dimensions: ["a", "a.b", "c.d"]
```

Support for flattened multiple dimensions was added in ES in `8.8` https://github.com/elastic/elasticsearch/pull/94842
