### ISSUE TITLE
[v3.0.0] Unable to set path_match in dynamic templates

### ISSUE THREAD

**Issue by andrewkroh** [elastic/package-spec#614]
Validation for explicit dynamic templates is failing under version 3.0.0. The error is:

`elasticsearch.index_template.mappings.dynamic_templates.INDEX.<dynamic_mapping_name>: Additional property path_match is not allowed`

https://github.com/elastic/integrations/issues/7811 contains an example of the problem. That specific use can be converted to a regular fields.yml definition, but I think this is a regression in any case. There are dynamic mappings that cannot be expressed through the fields.yml format as supported by package-spec so allowing the option to escape to standard Elasticsearch `dynamic_templates` is needed. For example, you cannot express two rules with the same `path_match` using the fields.yml spec because names must be unique.

```yaml
- name: o365.audit
  type: group
  fields:
    # INVALID: This is the desired mapping, but duplicates are not allowed.
    - name: ExchangeMetaData.*
      type: object
      object_type: double
      object_type_mapping_type: double
    - name: ExchangeMetaData.*
      type: object
      object_type: long
      object_type_mapping_type: long
      
# Error: checking package failed: linting package failed: found 1 validation error:
#   1. field "o365.audit.ExchangeMetaData.*" is defined multiple times for data stream "audit"
```
```
elasticsearch:
  index_template:
    mappings:
      dynamic: true
      dynamic_templates:
        - ExchangeMetaData_long:
            match_mapping_type: long
            path_match: o365.audit.ExchangeMetaData.*
            mapping:
              type: long
        - ExchangeMetaData_double:
            path_match: o365.audit.ExchangeMetaData.*
            mapping:
              type: double
```
