### ISSUE TITLE
Mixing 'external: ecs' with metric_type

### ISSUE THREAD

**Issue by andrewkroh** [elastic/package-spec#634]
ECS fields should be usable with TSDS. There are some metric fields defined in ECS. We want to use the ECS definition and add in `metric_type`, but this fails validation.

```yaml
- name: host.disk.read.bytes
  external: ecs
  metric_type: gauge
```

> file "packages/system/data_stream/diskio/fields/agent.yml" is invalid: field 0: type is required

**Comment by andrewkroh** [comment]
The workaround is to add the `type`.

```yaml
    - name: host.disk.read.bytes
      type: long
      external: ecs
      metric_type: gauge
```
