### ISSUE TITLE
[Change Proposal] Mapping size limit settings

### ISSUE THREAD

**Issue by pzl** [elastic/package-spec#640]
The [endpoint-package](https://github.com/elastic/endpoint-package) integration is often more complicated and needs access to more settings than a typical integration. While migration to package-spec 3.0 (from 1.0), we discovered two of those settings we may need restored. 

### Background

For historical context, Fleet used to (by default) set the `index.mapping.total_fields.limit` to `10000`. This was default across all integrations. [A discussion](https://github.com/elastic/kibana/issues/104620) was presented to no longer explicitly set this value, but let it fall back to the default value set in elasticsearch (which happens to be `1000`).  The [work was done here](https://github.com/elastic/kibana/pull/114101). This had to be [subsequently rolled back](https://github.com/elastic/kibana/pull/114299) because the endpoint-package does indeed use more than 1,000 fields for one of our mappings. The compromise was made that endpoint-package would specify its `total_fields` and `nested_fields` settings in its data stream mapping definition, so that fleet could re-introduce the change to remove its explicit setting.

### Data

This is the `manifest.yml` for that data stream in its entirety:

```yml
title: Endpoint Alerts
type: logs
elasticsearch:
  index_template:
    settings:
      index:
        mapping:
          nested_fields:
            limit: 80
          total_fields:
            limit: 5000
    mappings:
      dynamic: false
```

the errors caught by `elastic-package`:
```
   7. file "endpoint-package/package/endpoint/data_stream/alerts/manifest.yml" is invalid: field elasticsearch.index_template.settings.index.mapping: Additional property nested_fields is not allowed
   8. file "endpoint-package/package/endpoint/data_stream/alerts/manifest.yml" is invalid: field elasticsearch.index_template.settings.index.mapping: Additional property total_fields is not allowed
```

I would ask that these settings be supported, to continue compatibility
