### ISSUE TITLE
[Change Proposal] When the deployment_mode agentless is enabled we want the package to have additional fields populated.

### ISSUE THREAD

**Issue by seanrathier** [elastic/package-spec#795]
#### Motivation
We would like to have additional fields required to be populated in an integration package when the `deployment_mode` `agentless` is enabled. These fields are for identifying the organization, division, and team responsible for the integration. This information will be used to tag the agentless agent deployed in MKI so that we know who to contact when support is needed and for the teams to monitor their agentless agents.

#### Some open questions
- Should these new fields be siblings of the `deployment_mode.agentless`?
- Can we require fields to be populated by the integration developer if parent or sibling fields are enabled?

For example....
```
format_version: 3.0.0
name: aws
title: AWS
version: 2.13.1
...
policy_templates:
  - name: billing
    title: AWS Billing
    description: Collect billing metrics with Elastic Agent
    deployment_modes: # <---
      default:
        enabled: false
      agentless:
        enabled: true
        organization: 'Security'
        division: 'Cloud Security'
        team:  'Cloud Security Posture Management'
    data_streams:
      - billing
```

#### Related Issues
- https://github.com/elastic/package-spec/issues/684
- https://github.com/elastic/security-team/issues/10448
- https://github.com/elastic/agentless-api/issues/254
