### ISSUE TITLE
[Change Proposal] Add support for "next steps" links to be referenced in Kibana

### ISSUE THREAD

**Issue by criamico** [elastic/package-spec#832]
There are some cases when an integration developer might want to prompt the user to navigate to another area of kibana. 

For instance, in the case of Agentless policy configuration, the developer might need to display some next steps links that link to the kibana areas where the additional configuration will happen, as shown in the screenshot:
![Image](https://github.com/user-attachments/assets/a8127b6d-4c62-4f47-8b01-208508a82e61)

To be able to do an integration developer should be able to enumerate "next step" options for each package/policy template in [kibana manifest](https://github.com/elastic/package-spec/blob/5e844901c7cf688f011aaeedb2a17cc0b38b6458/spec/integration/manifest.spec.yml#L4):

```
policy_templates:
  - name: foo
    ...
    links:
      - title: Findings
        type: post_install_step
        content: "Consolidated view of security and compliance issues identified within your environment"
        url: "kbn:/app/enterprise_search/content/connector/{{connector_id}}/overview"
      - title: Add more accounts
        type: action
        url: "kbn:..."
```

There is also a special case of next steps that will navigate the user to the Connectors UI in Kibana and will reference connector ids for this:
![Image](https://github.com/user-attachments/assets/0dca3976-3ca8-47e1-8d17-f16fb1cf7d19)

These Connector Ids are currently static for the lifetime of a connector instance, (as they are ES Index document `_id` values for the `.elastic-connectors-v1` index) and they are being added as configurable to the policy "advanced" configuration, so they'll show up [here](https://github.com/elastic/integrations/blob/c55e51d9c8cdc64e4e10ca9c176894a74855d5a4/packages/elastic_connectors/manifest.yml#L49-L55). About connectors, they could be defined in one of these two ways:

- In the package policy ( no changes to package-spec)
- in package-spec, with the above suggested change to policy templates links, adding a templated variable `{{connector_id}}` that references the `vars` content.
