### ISSUE TITLE
[Change Proposal] Add support for ingest pipelines in transforms

### ISSUE THREAD

**Issue by jsoriano** [elastic/package-spec#833]
Transforms allow to define ingest pipelines, so documents are processed before ingestion. This allows for example to remove fields that are not relevant in the transform, or to adjust fields intended to have different values, as in https://github.com/elastic/elastic-package/issues/2218#issuecomment-2477128353.

This is partly supported now, a destination index can have a pipeline, but currently it needs to be hard-coded:
```
dest:
  index: "logs-ti_anomali_latest.threatstream-3"
  aliases:
    - alias: "logs-ti_anomali_latest.threatstream"
      move_on_creation: true
  pipeline: "1.23.0-latest_ioc"
```

We should allow to use templates there as we allow in other places, so configuration can be something like this:
```
dest:
  index: "logs-ti_anomali_latest.threatstream-3"
  aliases:
    - alias: "logs-ti_anomali_latest.threatstream"
      move_on_creation: true
  pipeline: '{{ IngestPipeline "latest_ioc" }}'
```

**Comment by jsoriano** [comment]
While the situation is improved, a workaround is proposed in https://github.com/elastic/elastic-package/issues/2552, to add a validation to check that the package provides the hard-coded pipeline.

**Comment by niraj-crest** [comment]
Could we please prioritize this issue?

We're currently blocked on two integrations that depend on transform pipelines:
- [GreyNoise Draft PR](https://github.com/elastic/integrations/pull/13786)
- [Google Threat Intelligence GA tracking issue](https://github.com/elastic/integrations/issues/14287)

Enabling support for pipelines would help us move both of these forward.

We’re okay with either of the following approaches:
- Using a pipeline template, as suggested here.
- Applying the workaround to add an elastic-package check for the pipeline, as discussed in [elastic/elastic-package#2552](https://github.com/elastic/elastic-package/issues/2552)

**Comment by kpollich** [comment]
Prioritizing this in our next iteration for tech definition.

**Comment by niraj-crest** [comment]
Thanks @kpollich,
Appreciate your support.

**Comment by mrodm** [comment]
Not totally sure these other fields could be set dynamically.

For instance, setting `dest.index` via template function, I think it would be needed to add the following parameters to the template function:
- data stream type (e.g. `logs`)
    - Although currently I think all of them are `logs`, but this could change.
- transform type (e.g. `latest`)
- data stream name (e.g. `threatstream`)
- suffix number to be updated, in the example `3`.

I think those should be set by the developers, so IIUC it probably does not make sense to add those.

And other packages do not follow that pattern. For instance, `ti_google_threat_intelligence` package define source.index and dest.index different ([link](https://github.com/elastic/integrations/blob/1a9b422d2da21d060d167eead02ee0fa6405fbca/packages/ti_google_threat_intelligence/elasticsearch/transform/rule_ioc_st/transform.yml)):
```yaml
source:
  index:
    - ".alerts-security.alerts-*"
  query:
    bool:
      ...
dest:
  index: "logs-ti_google_threat_intelligence.enriched_ioc_stream-1"
  aliases:
    - alias: "logs-ti_google_threat_intelligence.enriched_ioc_stream"
      move_on_creation: true
```


`tychon` package defines the destination index different too. It does not use the actual datastream name as part of the index name (`dest_arp` vs `arp`) ([link](https://github.com/elastic/integrations/blob/1a9b422d2da21d060d167eead02ee0fa6405fbca/packages/tychon/elasticsearch/transform/arp/transform.yml)):
```yaml
dest:
  index: "logs-tychon_latest.dest_arp-2"
  aliases:
    - alias: "logs-tychon_latest.arp"
      move_on_creation: true
```

Another example using a different approach is the `lmd` package ([link](https://github.com/elastic/integrations/blob/1a9b422d2da21d060d167eead02ee0fa6405fbca/packages/lmd/elasticsearch/transform/pivot_transform/transform.yml)):
```yaml
dest:
  index: "ml-rdp-lmd"
description: This transform runs hourly and collects windows RDP session information for Lateral Movement Detection package.
```
