### ISSUE TITLE
Prevent clashes between template fields and stream/input fields

### ISSUE THREAD

**Issue by jalvz** [elastic/package-spec#85]
Consider the following:

`manifest.yml`
```yml
policy_templates:
  - name: apm-server
    inputs:
      - type: apm
        vars:
          - name: name
            default: my-default-name
        template_path: ./agent/input/template.yml.hbs
```

`agent/input/template.yml.hbs`
```yml
name: {{name}}
```

There will be a clash between the `name` field in the template (package-defined) and the `name` field in the input (spec-defined)

Same thing occurs for data streams templates. This scenario should be detected and avoided.

**Comment by ruflin** [comment]
++ on detecting these potential clash. The part I don't fully understand how in the example you provided above a clash will happen. I think the two name properties are used at different places?

**Comment by jalvz** [comment]
They would end up in the same place in the policy, right under `inputs`

**Comment by ruflin** [comment]
I just create a config in Fleet to better understand what is happening. The output looks as following:

```
inputs:
  - id: 6f1b2b20-e21a-11ea-9f36-4d87277cce0a
    name: system-1
    revision: 1
    type: logfile
    use_output: default
    meta:
      package:
        name: system
        version: 0.5.3
    data_stream:
      namespace: default
    streams:
      - id: logfile-system.auth
        data_stream:
          dataset: system.auth
          type: logs
        paths:
          - /var/log/auth.log*
          - /var/log/secure*
```

I can see now that there is a `name: system-1` but this is not the policy template name from in here. This `name` is added by the user. Still, it will be a conflict in your case. What does the `name` property mean in your case?

Besides names, the other reserved fields I found are:

* id
* name
* type
* revision
* use_output
* data_stream
* streams

As you initially proposed, we should have validation for all these that they are not used inside the template.
