### ISSUE TITLE
[Change Proposal] Allow deployment modes to specify allowed inputs

### ISSUE THREAD

**Issue by jen-huang** [elastic/package-spec#874]
Related to deployment modes: https://github.com/elastic/package-spec/pull/738
Related to deployment modes input configuration: https://github.com/elastic/package-spec/issues/805

Following discussion in https://github.com/elastic/package-spec/issues/805, it was decided that Fleet will maintain a blocklist of inputs that are not allowed for agentless deployment modes. This was implemented in https://github.com/elastic/kibana/issues/202091.

In https://github.com/elastic/kibana/issues/211092, we saw that additional inputs needed to be blocked as new agentless integrations became available. This made us consider moving to an allowlist instead of a blocklist, but per investigation in https://github.com/elastic/kibana/issues/211275, the initial allowlist was too restrictive.

With this new information, it seems unsustainable for Fleet to define what is allowed for agentless integrations. We should move this to the package spec instead so that allowed inputs can be controlled by integrations. The existing `deployment_modes` property seems to be a good place to put it:

```yml
...
policy_templates:
  - name: billing
    title: AWS Billing
    description: Collect billing metrics with Elastic Agent
    deployment_modes:
      default:
        enabled: false
      agentless:
        enabled: true
        inputs: # <--- new field
          - aws/metrics
          - aws/s3
...
```

When `inputs` is specified under a deployment mode, Fleet should only show configuration for those inputs. If this field is not present, then the default behavior is to show all inputs specified by this policy template.

**Comment by jen-huang** [comment]
cc @qcorporation @jamiehynds @jsoriano WDYT?

**Comment by jsoriano** [comment]
On a first look this seems a bit redundant to me. Policy templates define their own inputs, so in principle they are already restricted.

I guess this can be an issue only if a policy template supports multiple deployment modes? In that case, if the policy template is only partially compatible with a deployment mode, wouldn't it be better to split it in two policy templates, so each one of them is fully compatible with the deployment modes they support?

I mean, instead of:
```
policy_templates:
  - name: billing
    title: AWS Billing
    description: Collect billing metrics with Elastic Agent
    deployment_modes:
      default:
        enabled: false
      agentless:
        enabled: true
        inputs: # <--- new field
          - aws/metrics
          - aws/s3
    inputs:
      - type: aws/metrics
        ...
      - type: aws/s3
        ...
      - type: httpjson
        ...
```

Do something like this, that is more explicit and already supported, even if may lead to some duplication:
```
policy_templates:
  - name: billing
    title: AWS Billing
    description: Collect billing metrics with Elastic Agent
    inputs:
      - type: aws/metrics
        ...
      - type: aws/s3
        ...
      - type: httpjson
        ...
  - name: billing_agentless
    title: AWS Billing
    description: Collect billing metrics with Elastic Agent
    deployment_modes:
      default:
        enabled: false
      agentless:
        enabled: true
    inputs:
      - type: aws/metrics
        ...
      - type: aws/s3
        ...
```

If we don't want this duplication, and we definitely want to add something to explicitly support this, I think it would be better to make this restriction part of the input:
```
policy_templates:
  - name: billing
    title: AWS Billing
    description: Collect billing metrics with Elastic Agent
    deployment_modes:
      default:
        enabled: false
      agentless:
        enabled: true
    inputs:
      - type: aws/metrics
        ...
      - type: aws/s3
        ...
      - type: httpjson
        deployment_modes: ['default']
        ...
```
